config/routes.rb
Rails.application.routes.draw do
  mount Attachinary::Engine => "/attachinary"

  devise_for :users
root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

get "/clients" => "clients#index"
get "/clients/new" => "clients#new"
get "/clients/:id" => "clients#show"

get "/team" => "pages#team"
get "/contact" => "pages#joinus"

resources :clients #, points d'entrée nécessaires slt only (:new, :create, :index, :show)

=begin
# les 7 points d'entrée du routing CRUD dans Rails
#Read action routes
get "/clients" => "clients#index"
get "/clients/:id" => "clients#show"

#Create action routes
get "/clients/new" => "clients#new" #afficher formulaire pr creer client
post "/clients" => "clients#create" #action va  recuperer les params du formulaire et créer en base de données le client

#Update action routes
get "/clients/:id/edit" => "clients#edit" #affiche formulaire pré rempli d'un produit existant
patch "/clients/:id" => "clients#create" #update un produit en base

#Delete action routes
delete "/clients/:id" => "clients#destroy" #par convention, la method du controller sappelle destroy (pour differencier avec delete)
=end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
 has_attachment :photo
 has_many :upvotes
belongs_to :user

validates :user, presence: true
validates :name, presence: true, uniqueness: true
#pour écrire un client, le nom doit être présent et unique
validates :url, presence: true, uniqueness: true
validates :category, inclusion: { in: %w(CEO CFO CMO),
    message: "%{value} is not a valid category" }

end

app/models/product.rb
class Product < ApplicationRecord
end

app/models/upvote.rb
class Upvote < ApplicationRecord
  belongs_to :user
  belongs_to :client
end

app/models/user.rb
class User < ApplicationRecord

has_many :clients
has_many :upvotes
has_attachment :avatar

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  #protect_from_forgery with: :exception
 before_filter :initialize_user

 before_action :authenticate_user! #Liste blanche
 #attention ligne clé du site

 before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,        keys: [:avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end

  def initialize_user
    @client = Client.new
 end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
skip_before_action :authenticate_user!, only: [ :index, :show]
before_action :find_client, only: [:show, :edit, :update, :destroy]
#pour ne pas répéter le code recup id du formulaire
#cela signifie "Avant d'appeler l'action show, edit..., je vais appeler la methode find_product qui chope l'id du formulaire"

def index
  if params[:category]
    @clients = Client.where(category: params[:category])
  else
    @clients = Client.all
  end
end

def show
  #si quelqu'un écrit 11, alors cest 11
  #on va dire que l'id cest l'indice du tableau (car on a pas encore de data base)

#methode params id à mettre en integer pour le lire dans le tableau

end

# methode qui va afficher formulaire
# elle est là pour renvoyer la vue new.html.erb avec le formulaire
  def new
  end

#recup params du formulaire et créer en base
  def create
        #binding.pry
        @client = Client.new(client_params)
        @client.user = current_user

    # la methode va ensuite sauver le client, on le save en base
        if @client.save #si jarrive à sauver le produit en base, ie sil passe les validations du Models/concerns/client.rb

        #et après, on redirige vers la page de listing de clients
        redirect_to clients_path

      else
        render :new
      end
        #si marche pas, renvoie le template new avec le formulaire qui a déjà des infos
        # BUT du IF elese = évite de ne rien prendre en compte dans l'affichage lors que la validation du produit échoue

  #on met un point darret là
  end

#afficher le formulaire pré rempli
  def edit
     #elle recup l'id dans l'URL
    # elle renvoie un template dans vues qui q le mm nom qu elle
  end

#recup infos et modifie en bas
  def update
    if @client.update(client_params)
      redirect_to clients_path
    else
      render :edit
    end
  end

  def destroy
#binding.pry
@client.destroy
redirect_to clients_path
  end

  private

  def client_params
    params.require(:client).permit(:name,:url,:tagline,:category,:photo,:user)
    #on filtre les parametres à input en base
    #on empeche l'utilisateur d'ajouter nimporte quoi dans notre base
  end

def find_client
  @client = Client.find(params[:id])


end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
skip_before_action :authenticate_user!
  def home
    #render plain: "Welcome!!!"
    @today = Date.today
  end

def team
@members = ["P", "J", "ML"]
  end

  def joinus
    render plain: "Send us a mail!!!"
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index
@products = Product.all
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/clients/_form.html.erb
<%= simple_form_for @client do |f| %>

  <%= f.input :name, placeholder: 'Enter name',label:"Which client?" %>
  <%= f.input :url, placeholder: 'Enter url',label:"Which URL?" %>
  <%= f.input :tagline, placeholder: 'Enter tagline',label:"Which tagline?" %>
  <%= f.input :category, collection: ["CEO", "CFO", "CMO"], prompt:"Which category?" %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.button :submit,"Add", class:"btn btn-primary" %>



<% end %>

app/views/clients/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

  <h1 class="text-center">Edit the client </h1>
  </h1>

<%= render "form" %>

    </div>
  </div>
</div>

app/views/clients/index.html.erb
<div class="container" class="text-center">
<div class="row">
  <div class="col-xs-12 col-sm-10 col-sm-offset-1">
    <h1 class="text-center">Confidential list of clients</h1>


        <%= @clients.each do |client| %>

          <div class="product">
  <div class='product-upvote'>
    <div class="product-arrow"></div>
    <div class='product-count'>0</div>
  </div>

<% if client.photo? %>
<%= cl_image_tag(client.photo.path, height: 117, width: 175, crop: :fill, class: "product-image") %>
<% else %>


  <img src="http://unsplash.it/300/200?random" alt="kudoz" class="product-image hidden-xs">
  <% end %>
  <div class='product-body'>
    <h3><%=client.name %> </h3>
    <p> <%= client.tagline %> </p>
  </div>
  <ul class="list-inline product-controls">

    <li>
    <%= link_to client_path(client) do  %>
    <i class="fa fa-eye"></i>
    <% end %>

      <li>
    <%= link_to edit_client_path(client) do  %>
    <i class="fa fa-pencil"></i>
    <% end %>

  <li>
    <%= link_to client_path(client), method: :delete do  %>
    <i class="fa fa-trash"></i>
    <% end %>

  </ul>
</div>


    <% end %>



  </div>
</div>

app/views/clients/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">

  <h1 class="text-center">So, who's your next client? </h1>
  </h1>

<%= render "form" %>

<!--
    <form action="/clients" method="post">
<div class="form-group">
<label for="name">Name of your client client</label>
    <input class="form-control" type="text" name="client[name]" placeholder="Julien" id="name">
</div>
<div class="form-group">
<label for="url">URL</label>
    <input class="form-control" type="text" name="client[url]" placeholder="http://" id="url">
</div>
    <input type="submit" value="Add" class="btn btn-primary">

    </form>
-->

    </div>
  </div>
</div>

app/views/clients/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= @client.photo? ? cloudinary_url(@client.photo.path, width: 1000, height: 700) : image_path("background.jpg") %>');">
  <div class="banner-content">
    <h1> <%= @client.name %></h1>
    <p> <%= @client.tagline %> <br> </p>
    <span class="label label-default">
    <%= @client.category %>
    </span>
    <br>

<% if @client.user %>
    <p>
      Posted by <%= @client.user.email %>
    </p>
<% end %>


    <%= link_to "Get it",@client.url,class:"btn btn-primary btn-lg" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>Alpha Project</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
<%= render "shared/navbar" %>

<%= render "shared/flashes" %>



    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('<%= image_path "background.jpg" %>');">
  <div class="banner-content">
    <h1>Save your money</h1>
    <p>Find out new solutions</p>
    <%= link_to "All Clients",clients_path,class:"btn btn-primary btn-lg" %>
  </div>
</div>

<div class="container padded">
      <div class="row">
              <div class="col-xs-12 col-sm-4 card-category">
                <%= link_to "CEO", clients_path(category:"CEO"), class:"card-category ceo" %>
              </div>
               <div class="col-xs-12 col-sm-4">
                <%= link_to "CFO", clients_path(category:"CFO"), class:"card-category cfo" %>
              </div>
               <div class="col-xs-12 col-sm-4">
                <%= link_to "CMO", clients_path(category:"CMO"), class:"card-category cmo" %>
              </div>


      </div>
</div>

app/views/pages/team.html.erb
<div class="container" text-center>

<h1>Please meet the team members</h1>

<%= cl_image_tag "bxruqdanuu2rbwlyrcc2", width: 400, height: 200 %>

<ul>

    <%= @members.each do |member| %>
     <li> Member: <%= member%> </li>
<% end %>

</ul>

</div>

app/views/products/index.html.erb
<h1> Les produits </h1>

<% @products.each do |product|
  %>

<p>
<%= product.name %>

</p>

<% end %>

app/views/shared/_flashes.html.erb
 <!-- This file is in `app/views/shared/_flashes.html.erb` -->

<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "alpha.jpg" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Text link -->

<% if user_signed_in? %>
    <!-- Text link -->
    <%= link_to "All clients", clients_path, class:"navbar-wagon-item navbar-wagon-link" %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">

      <% if current_user.avatar? %>
      <%= cl_image_tag current_user.avatar.path, width: 60, height: 60, crop: :fill, class: 'avatar dropdown-toggle', id: 'navbar-wagon-menu', :'data-toggle' => 'dropdown' %>
      <% else %>
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <% end %>

        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Dashboard</a></li>
          <li>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
   <%= link_to "Add client", new_client_path, class: "navbar-wagon-item navbar-wagon-button" %>


<% else %>

<%= link_to "Connect", new_user_session_path, class:"navbar-wagon-item navbar-wagon-link" %>
<%= link_to "Inscription", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-link" %>


<% end %>
  </div>



  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>